// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseType.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_BaseType_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_BaseType_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_BaseType_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_BaseType_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_BaseType_2eproto;
namespace pb {
class QuaternionStruct;
class QuaternionStructDefaultTypeInternal;
extern QuaternionStructDefaultTypeInternal _QuaternionStruct_default_instance_;
class Vector3Struct;
class Vector3StructDefaultTypeInternal;
extern Vector3StructDefaultTypeInternal _Vector3Struct_default_instance_;
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
template<> ::pb::QuaternionStruct* Arena::CreateMaybeMessage<::pb::QuaternionStruct>(Arena*);
template<> ::pb::Vector3Struct* Arena::CreateMaybeMessage<::pb::Vector3Struct>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace pb {

// ===================================================================

class Vector3Struct PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.Vector3Struct) */ {
 public:
  inline Vector3Struct() : Vector3Struct(nullptr) {}
  virtual ~Vector3Struct();

  Vector3Struct(const Vector3Struct& from);
  Vector3Struct(Vector3Struct&& from) noexcept
    : Vector3Struct() {
    *this = ::std::move(from);
  }

  inline Vector3Struct& operator=(const Vector3Struct& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vector3Struct& operator=(Vector3Struct&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Vector3Struct& default_instance();

  static inline const Vector3Struct* internal_default_instance() {
    return reinterpret_cast<const Vector3Struct*>(
               &_Vector3Struct_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Vector3Struct& a, Vector3Struct& b) {
    a.Swap(&b);
  }
  inline void Swap(Vector3Struct* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vector3Struct* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Vector3Struct* New() const final {
    return CreateMaybeMessage<Vector3Struct>(nullptr);
  }

  Vector3Struct* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Vector3Struct>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Vector3Struct& from);
  void MergeFrom(const Vector3Struct& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vector3Struct* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.Vector3Struct";
  }
  protected:
  explicit Vector3Struct(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_BaseType_2eproto);
    return ::descriptor_table_BaseType_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:pb.Vector3Struct)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float x_;
  float y_;
  float z_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_BaseType_2eproto;
};
// -------------------------------------------------------------------

class QuaternionStruct PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.QuaternionStruct) */ {
 public:
  inline QuaternionStruct() : QuaternionStruct(nullptr) {}
  virtual ~QuaternionStruct();

  QuaternionStruct(const QuaternionStruct& from);
  QuaternionStruct(QuaternionStruct&& from) noexcept
    : QuaternionStruct() {
    *this = ::std::move(from);
  }

  inline QuaternionStruct& operator=(const QuaternionStruct& from) {
    CopyFrom(from);
    return *this;
  }
  inline QuaternionStruct& operator=(QuaternionStruct&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const QuaternionStruct& default_instance();

  static inline const QuaternionStruct* internal_default_instance() {
    return reinterpret_cast<const QuaternionStruct*>(
               &_QuaternionStruct_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(QuaternionStruct& a, QuaternionStruct& b) {
    a.Swap(&b);
  }
  inline void Swap(QuaternionStruct* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QuaternionStruct* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline QuaternionStruct* New() const final {
    return CreateMaybeMessage<QuaternionStruct>(nullptr);
  }

  QuaternionStruct* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<QuaternionStruct>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const QuaternionStruct& from);
  void MergeFrom(const QuaternionStruct& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(QuaternionStruct* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.QuaternionStruct";
  }
  protected:
  explicit QuaternionStruct(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_BaseType_2eproto);
    return ::descriptor_table_BaseType_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
    kWFieldNumber = 4,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // float w = 4;
  void clear_w();
  float w() const;
  void set_w(float value);
  private:
  float _internal_w() const;
  void _internal_set_w(float value);
  public:

  // @@protoc_insertion_point(class_scope:pb.QuaternionStruct)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float x_;
  float y_;
  float z_;
  float w_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_BaseType_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Vector3Struct

// float x = 1;
inline void Vector3Struct::clear_x() {
  x_ = 0;
}
inline float Vector3Struct::_internal_x() const {
  return x_;
}
inline float Vector3Struct::x() const {
  // @@protoc_insertion_point(field_get:pb.Vector3Struct.x)
  return _internal_x();
}
inline void Vector3Struct::_internal_set_x(float value) {
  
  x_ = value;
}
inline void Vector3Struct::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:pb.Vector3Struct.x)
}

// float y = 2;
inline void Vector3Struct::clear_y() {
  y_ = 0;
}
inline float Vector3Struct::_internal_y() const {
  return y_;
}
inline float Vector3Struct::y() const {
  // @@protoc_insertion_point(field_get:pb.Vector3Struct.y)
  return _internal_y();
}
inline void Vector3Struct::_internal_set_y(float value) {
  
  y_ = value;
}
inline void Vector3Struct::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:pb.Vector3Struct.y)
}

// float z = 3;
inline void Vector3Struct::clear_z() {
  z_ = 0;
}
inline float Vector3Struct::_internal_z() const {
  return z_;
}
inline float Vector3Struct::z() const {
  // @@protoc_insertion_point(field_get:pb.Vector3Struct.z)
  return _internal_z();
}
inline void Vector3Struct::_internal_set_z(float value) {
  
  z_ = value;
}
inline void Vector3Struct::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:pb.Vector3Struct.z)
}

// -------------------------------------------------------------------

// QuaternionStruct

// float x = 1;
inline void QuaternionStruct::clear_x() {
  x_ = 0;
}
inline float QuaternionStruct::_internal_x() const {
  return x_;
}
inline float QuaternionStruct::x() const {
  // @@protoc_insertion_point(field_get:pb.QuaternionStruct.x)
  return _internal_x();
}
inline void QuaternionStruct::_internal_set_x(float value) {
  
  x_ = value;
}
inline void QuaternionStruct::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:pb.QuaternionStruct.x)
}

// float y = 2;
inline void QuaternionStruct::clear_y() {
  y_ = 0;
}
inline float QuaternionStruct::_internal_y() const {
  return y_;
}
inline float QuaternionStruct::y() const {
  // @@protoc_insertion_point(field_get:pb.QuaternionStruct.y)
  return _internal_y();
}
inline void QuaternionStruct::_internal_set_y(float value) {
  
  y_ = value;
}
inline void QuaternionStruct::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:pb.QuaternionStruct.y)
}

// float z = 3;
inline void QuaternionStruct::clear_z() {
  z_ = 0;
}
inline float QuaternionStruct::_internal_z() const {
  return z_;
}
inline float QuaternionStruct::z() const {
  // @@protoc_insertion_point(field_get:pb.QuaternionStruct.z)
  return _internal_z();
}
inline void QuaternionStruct::_internal_set_z(float value) {
  
  z_ = value;
}
inline void QuaternionStruct::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:pb.QuaternionStruct.z)
}

// float w = 4;
inline void QuaternionStruct::clear_w() {
  w_ = 0;
}
inline float QuaternionStruct::_internal_w() const {
  return w_;
}
inline float QuaternionStruct::w() const {
  // @@protoc_insertion_point(field_get:pb.QuaternionStruct.w)
  return _internal_w();
}
inline void QuaternionStruct::_internal_set_w(float value) {
  
  w_ = value;
}
inline void QuaternionStruct::set_w(float value) {
  _internal_set_w(value);
  // @@protoc_insertion_point(field_set:pb.QuaternionStruct.w)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_BaseType_2eproto
