// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login_db_msg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_login_5fdb_5fmsg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_login_5fdb_5fmsg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "gate_login_msg.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_login_5fdb_5fmsg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_login_5fdb_5fmsg_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_login_5fdb_5fmsg_2eproto;
namespace pb {
class SSDB2LLoginAuthRsp;
class SSDB2LLoginAuthRspDefaultTypeInternal;
extern SSDB2LLoginAuthRspDefaultTypeInternal _SSDB2LLoginAuthRsp_default_instance_;
class SSLogin2DLoginAuthReq;
class SSLogin2DLoginAuthReqDefaultTypeInternal;
extern SSLogin2DLoginAuthReqDefaultTypeInternal _SSLogin2DLoginAuthReq_default_instance_;
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
template<> ::pb::SSDB2LLoginAuthRsp* Arena::CreateMaybeMessage<::pb::SSDB2LLoginAuthRsp>(Arena*);
template<> ::pb::SSLogin2DLoginAuthReq* Arena::CreateMaybeMessage<::pb::SSLogin2DLoginAuthReq>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace pb {

enum SS_LOGIN_DB_CMD : int {
  SS_LOGIN_DB_DEFAULT = 0,
  SS_LOGIN_DB_AUTH_REQ = 301,
  SS_DB_LOGIN_AUTH_RSP = 302,
  SS_LOGIN_DB_CMD_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  SS_LOGIN_DB_CMD_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool SS_LOGIN_DB_CMD_IsValid(int value);
constexpr SS_LOGIN_DB_CMD SS_LOGIN_DB_CMD_MIN = SS_LOGIN_DB_DEFAULT;
constexpr SS_LOGIN_DB_CMD SS_LOGIN_DB_CMD_MAX = SS_DB_LOGIN_AUTH_RSP;
constexpr int SS_LOGIN_DB_CMD_ARRAYSIZE = SS_LOGIN_DB_CMD_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SS_LOGIN_DB_CMD_descriptor();
template<typename T>
inline const std::string& SS_LOGIN_DB_CMD_Name(T enum_t_value) {
  static_assert(::std::is_same<T, SS_LOGIN_DB_CMD>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function SS_LOGIN_DB_CMD_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    SS_LOGIN_DB_CMD_descriptor(), enum_t_value);
}
inline bool SS_LOGIN_DB_CMD_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, SS_LOGIN_DB_CMD* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<SS_LOGIN_DB_CMD>(
    SS_LOGIN_DB_CMD_descriptor(), name, value);
}
// ===================================================================

class SSLogin2DLoginAuthReq PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.SSLogin2DLoginAuthReq) */ {
 public:
  inline SSLogin2DLoginAuthReq() : SSLogin2DLoginAuthReq(nullptr) {}
  virtual ~SSLogin2DLoginAuthReq();

  SSLogin2DLoginAuthReq(const SSLogin2DLoginAuthReq& from);
  SSLogin2DLoginAuthReq(SSLogin2DLoginAuthReq&& from) noexcept
    : SSLogin2DLoginAuthReq() {
    *this = ::std::move(from);
  }

  inline SSLogin2DLoginAuthReq& operator=(const SSLogin2DLoginAuthReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline SSLogin2DLoginAuthReq& operator=(SSLogin2DLoginAuthReq&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SSLogin2DLoginAuthReq& default_instance();

  static inline const SSLogin2DLoginAuthReq* internal_default_instance() {
    return reinterpret_cast<const SSLogin2DLoginAuthReq*>(
               &_SSLogin2DLoginAuthReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SSLogin2DLoginAuthReq& a, SSLogin2DLoginAuthReq& b) {
    a.Swap(&b);
  }
  inline void Swap(SSLogin2DLoginAuthReq* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SSLogin2DLoginAuthReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SSLogin2DLoginAuthReq* New() const final {
    return CreateMaybeMessage<SSLogin2DLoginAuthReq>(nullptr);
  }

  SSLogin2DLoginAuthReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SSLogin2DLoginAuthReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SSLogin2DLoginAuthReq& from);
  void MergeFrom(const SSLogin2DLoginAuthReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SSLogin2DLoginAuthReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.SSLogin2DLoginAuthReq";
  }
  protected:
  explicit SSLogin2DLoginAuthReq(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_login_5fdb_5fmsg_2eproto);
    return ::descriptor_table_login_5fdb_5fmsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kReqFieldNumber = 2,
    kRequestIdFieldNumber = 1,
  };
  // .pb.SSGate2LLoginAuthReq req = 2;
  bool has_req() const;
  private:
  bool _internal_has_req() const;
  public:
  void clear_req();
  const ::pb::SSGate2LLoginAuthReq& req() const;
  ::pb::SSGate2LLoginAuthReq* release_req();
  ::pb::SSGate2LLoginAuthReq* mutable_req();
  void set_allocated_req(::pb::SSGate2LLoginAuthReq* req);
  private:
  const ::pb::SSGate2LLoginAuthReq& _internal_req() const;
  ::pb::SSGate2LLoginAuthReq* _internal_mutable_req();
  public:
  void unsafe_arena_set_allocated_req(
      ::pb::SSGate2LLoginAuthReq* req);
  ::pb::SSGate2LLoginAuthReq* unsafe_arena_release_req();

  // uint32 request_id = 1;
  void clear_request_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 request_id() const;
  void set_request_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_request_id() const;
  void _internal_set_request_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:pb.SSLogin2DLoginAuthReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::pb::SSGate2LLoginAuthReq* req_;
  ::PROTOBUF_NAMESPACE_ID::uint32 request_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_login_5fdb_5fmsg_2eproto;
};
// -------------------------------------------------------------------

class SSDB2LLoginAuthRsp PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.SSDB2LLoginAuthRsp) */ {
 public:
  inline SSDB2LLoginAuthRsp() : SSDB2LLoginAuthRsp(nullptr) {}
  virtual ~SSDB2LLoginAuthRsp();

  SSDB2LLoginAuthRsp(const SSDB2LLoginAuthRsp& from);
  SSDB2LLoginAuthRsp(SSDB2LLoginAuthRsp&& from) noexcept
    : SSDB2LLoginAuthRsp() {
    *this = ::std::move(from);
  }

  inline SSDB2LLoginAuthRsp& operator=(const SSDB2LLoginAuthRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline SSDB2LLoginAuthRsp& operator=(SSDB2LLoginAuthRsp&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SSDB2LLoginAuthRsp& default_instance();

  static inline const SSDB2LLoginAuthRsp* internal_default_instance() {
    return reinterpret_cast<const SSDB2LLoginAuthRsp*>(
               &_SSDB2LLoginAuthRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SSDB2LLoginAuthRsp& a, SSDB2LLoginAuthRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(SSDB2LLoginAuthRsp* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SSDB2LLoginAuthRsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SSDB2LLoginAuthRsp* New() const final {
    return CreateMaybeMessage<SSDB2LLoginAuthRsp>(nullptr);
  }

  SSDB2LLoginAuthRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SSDB2LLoginAuthRsp>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SSDB2LLoginAuthRsp& from);
  void MergeFrom(const SSDB2LLoginAuthRsp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SSDB2LLoginAuthRsp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.SSDB2LLoginAuthRsp";
  }
  protected:
  explicit SSDB2LLoginAuthRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_login_5fdb_5fmsg_2eproto);
    return ::descriptor_table_login_5fdb_5fmsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRspFieldNumber = 2,
    kRequestIdFieldNumber = 1,
  };
  // .pb.SSLogin2GLoginAuthRsp rsp = 2;
  bool has_rsp() const;
  private:
  bool _internal_has_rsp() const;
  public:
  void clear_rsp();
  const ::pb::SSLogin2GLoginAuthRsp& rsp() const;
  ::pb::SSLogin2GLoginAuthRsp* release_rsp();
  ::pb::SSLogin2GLoginAuthRsp* mutable_rsp();
  void set_allocated_rsp(::pb::SSLogin2GLoginAuthRsp* rsp);
  private:
  const ::pb::SSLogin2GLoginAuthRsp& _internal_rsp() const;
  ::pb::SSLogin2GLoginAuthRsp* _internal_mutable_rsp();
  public:
  void unsafe_arena_set_allocated_rsp(
      ::pb::SSLogin2GLoginAuthRsp* rsp);
  ::pb::SSLogin2GLoginAuthRsp* unsafe_arena_release_rsp();

  // uint32 request_id = 1;
  void clear_request_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 request_id() const;
  void set_request_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_request_id() const;
  void _internal_set_request_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:pb.SSDB2LLoginAuthRsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::pb::SSLogin2GLoginAuthRsp* rsp_;
  ::PROTOBUF_NAMESPACE_ID::uint32 request_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_login_5fdb_5fmsg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SSLogin2DLoginAuthReq

// uint32 request_id = 1;
inline void SSLogin2DLoginAuthReq::clear_request_id() {
  request_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SSLogin2DLoginAuthReq::_internal_request_id() const {
  return request_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SSLogin2DLoginAuthReq::request_id() const {
  // @@protoc_insertion_point(field_get:pb.SSLogin2DLoginAuthReq.request_id)
  return _internal_request_id();
}
inline void SSLogin2DLoginAuthReq::_internal_set_request_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  request_id_ = value;
}
inline void SSLogin2DLoginAuthReq::set_request_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_request_id(value);
  // @@protoc_insertion_point(field_set:pb.SSLogin2DLoginAuthReq.request_id)
}

// .pb.SSGate2LLoginAuthReq req = 2;
inline bool SSLogin2DLoginAuthReq::_internal_has_req() const {
  return this != internal_default_instance() && req_ != nullptr;
}
inline bool SSLogin2DLoginAuthReq::has_req() const {
  return _internal_has_req();
}
inline const ::pb::SSGate2LLoginAuthReq& SSLogin2DLoginAuthReq::_internal_req() const {
  const ::pb::SSGate2LLoginAuthReq* p = req_;
  return p != nullptr ? *p : reinterpret_cast<const ::pb::SSGate2LLoginAuthReq&>(
      ::pb::_SSGate2LLoginAuthReq_default_instance_);
}
inline const ::pb::SSGate2LLoginAuthReq& SSLogin2DLoginAuthReq::req() const {
  // @@protoc_insertion_point(field_get:pb.SSLogin2DLoginAuthReq.req)
  return _internal_req();
}
inline void SSLogin2DLoginAuthReq::unsafe_arena_set_allocated_req(
    ::pb::SSGate2LLoginAuthReq* req) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(req_);
  }
  req_ = req;
  if (req) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:pb.SSLogin2DLoginAuthReq.req)
}
inline ::pb::SSGate2LLoginAuthReq* SSLogin2DLoginAuthReq::release_req() {
  
  ::pb::SSGate2LLoginAuthReq* temp = req_;
  req_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::pb::SSGate2LLoginAuthReq* SSLogin2DLoginAuthReq::unsafe_arena_release_req() {
  // @@protoc_insertion_point(field_release:pb.SSLogin2DLoginAuthReq.req)
  
  ::pb::SSGate2LLoginAuthReq* temp = req_;
  req_ = nullptr;
  return temp;
}
inline ::pb::SSGate2LLoginAuthReq* SSLogin2DLoginAuthReq::_internal_mutable_req() {
  
  if (req_ == nullptr) {
    auto* p = CreateMaybeMessage<::pb::SSGate2LLoginAuthReq>(GetArena());
    req_ = p;
  }
  return req_;
}
inline ::pb::SSGate2LLoginAuthReq* SSLogin2DLoginAuthReq::mutable_req() {
  // @@protoc_insertion_point(field_mutable:pb.SSLogin2DLoginAuthReq.req)
  return _internal_mutable_req();
}
inline void SSLogin2DLoginAuthReq::set_allocated_req(::pb::SSGate2LLoginAuthReq* req) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(req_);
  }
  if (req) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(req)->GetArena();
    if (message_arena != submessage_arena) {
      req = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, req, submessage_arena);
    }
    
  } else {
    
  }
  req_ = req;
  // @@protoc_insertion_point(field_set_allocated:pb.SSLogin2DLoginAuthReq.req)
}

// -------------------------------------------------------------------

// SSDB2LLoginAuthRsp

// uint32 request_id = 1;
inline void SSDB2LLoginAuthRsp::clear_request_id() {
  request_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SSDB2LLoginAuthRsp::_internal_request_id() const {
  return request_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SSDB2LLoginAuthRsp::request_id() const {
  // @@protoc_insertion_point(field_get:pb.SSDB2LLoginAuthRsp.request_id)
  return _internal_request_id();
}
inline void SSDB2LLoginAuthRsp::_internal_set_request_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  request_id_ = value;
}
inline void SSDB2LLoginAuthRsp::set_request_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_request_id(value);
  // @@protoc_insertion_point(field_set:pb.SSDB2LLoginAuthRsp.request_id)
}

// .pb.SSLogin2GLoginAuthRsp rsp = 2;
inline bool SSDB2LLoginAuthRsp::_internal_has_rsp() const {
  return this != internal_default_instance() && rsp_ != nullptr;
}
inline bool SSDB2LLoginAuthRsp::has_rsp() const {
  return _internal_has_rsp();
}
inline const ::pb::SSLogin2GLoginAuthRsp& SSDB2LLoginAuthRsp::_internal_rsp() const {
  const ::pb::SSLogin2GLoginAuthRsp* p = rsp_;
  return p != nullptr ? *p : reinterpret_cast<const ::pb::SSLogin2GLoginAuthRsp&>(
      ::pb::_SSLogin2GLoginAuthRsp_default_instance_);
}
inline const ::pb::SSLogin2GLoginAuthRsp& SSDB2LLoginAuthRsp::rsp() const {
  // @@protoc_insertion_point(field_get:pb.SSDB2LLoginAuthRsp.rsp)
  return _internal_rsp();
}
inline void SSDB2LLoginAuthRsp::unsafe_arena_set_allocated_rsp(
    ::pb::SSLogin2GLoginAuthRsp* rsp) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(rsp_);
  }
  rsp_ = rsp;
  if (rsp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:pb.SSDB2LLoginAuthRsp.rsp)
}
inline ::pb::SSLogin2GLoginAuthRsp* SSDB2LLoginAuthRsp::release_rsp() {
  
  ::pb::SSLogin2GLoginAuthRsp* temp = rsp_;
  rsp_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::pb::SSLogin2GLoginAuthRsp* SSDB2LLoginAuthRsp::unsafe_arena_release_rsp() {
  // @@protoc_insertion_point(field_release:pb.SSDB2LLoginAuthRsp.rsp)
  
  ::pb::SSLogin2GLoginAuthRsp* temp = rsp_;
  rsp_ = nullptr;
  return temp;
}
inline ::pb::SSLogin2GLoginAuthRsp* SSDB2LLoginAuthRsp::_internal_mutable_rsp() {
  
  if (rsp_ == nullptr) {
    auto* p = CreateMaybeMessage<::pb::SSLogin2GLoginAuthRsp>(GetArena());
    rsp_ = p;
  }
  return rsp_;
}
inline ::pb::SSLogin2GLoginAuthRsp* SSDB2LLoginAuthRsp::mutable_rsp() {
  // @@protoc_insertion_point(field_mutable:pb.SSDB2LLoginAuthRsp.rsp)
  return _internal_mutable_rsp();
}
inline void SSDB2LLoginAuthRsp::set_allocated_rsp(::pb::SSLogin2GLoginAuthRsp* rsp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(rsp_);
  }
  if (rsp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(rsp)->GetArena();
    if (message_arena != submessage_arena) {
      rsp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rsp, submessage_arena);
    }
    
  } else {
    
  }
  rsp_ = rsp;
  // @@protoc_insertion_point(field_set_allocated:pb.SSDB2LLoginAuthRsp.rsp)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::pb::SS_LOGIN_DB_CMD> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::pb::SS_LOGIN_DB_CMD>() {
  return ::pb::SS_LOGIN_DB_CMD_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_login_5fdb_5fmsg_2eproto
